[package]
name = "memes-auction"
version = "0.0.1"
authors = ["Rares"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.34.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.34.1"
