[package]
name = "memes-auction"
version = "0.0.1"
authors = ["Rares Serban <raresserban96@outlook.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.25.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.25.0"
