[package]
name = "memes-creator-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.memes-creator]
path = ".."

[dependencies.elrond-wasm]
version = "0.20.1"

[dependencies.elrond-wasm-debug]
version = "0.20.1"
