[package]
name = "memes-voting"
version = "0.0.1"
authors = ["Rares"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.29.3"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.3"

[dependencies.elrond-wasm-modules]
version = "0.29.3"
