[package]
name = "memes-auction-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.memes-auction]
path = ".."

[dependencies.elrond-wasm]
version = "0.27.4"

[dependencies.elrond-wasm-debug]
version = "0.27.4"
