[package]
name = "memes-staking"
version = "0.0.0"
authors = [ "Rares",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.34.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.34.0"

[dependencies.elrond-wasm-modules]
version = "0.34.0"
