[package]
name = "memes-voting-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.memes-voting]
path = ".."

[dependencies.elrond-wasm]
version = "0.25.0"

[dependencies.elrond-wasm-debug]
version = "0.25.0"
