[package]
name = "crowdfunding-abi"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2018"
publish = false

[dependencies.crowdfunding]
path = ".."

[dependencies.elrond-wasm]
version = "0.17.2"

[dependencies.elrond-wasm-debug]
version = "0.17.2"
